# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-lldap
    main: ./cmd/terraform-provider-lldap/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    binary: "{{ .ProjectName }}_v{{ .Version }}"
    ldflags:
      - -s -w -X main.Version={{.Version}}
  - id: lldap-cli
    main: ./cmd/lldap-cli/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    binary: lldap-cli
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - id: terraform-provider-lldap
    builds:
      - terraform-provider-lldap
    format: zip
    name_template: "terraform-provider-lldap_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: lldap-cli
    builds:
      - lldap-cli
    format: zip
    name_template: "lldap-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  use: github

checksum:
  name_template: "checksums_{{ .Version }}_SHA256SUMS"

signs:
  - artifacts: checksum
    output: true
    args:
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  draft: true
