name: TestRelease

on:
  push:
    #tags:
    #  - "v*.*.*"
    branches:
      - release-test

jobs:
  test-release:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
      - name: GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}
        run: goreleaser release --timeout=5m --skip-publish --draft --snapshot
